language: python
cache: apt
sudo: false
addons:
  apt:
    packages:
    - language-pack-en-base
    - language-pack-de-base
    - language-pack-ja-base
branches:
  only:
  - src
python:
- 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_993add234cfd_key -iv $encrypted_993add234cfd_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'Matthias Lambrecht'
- git config --global user.email 'mats.lan.pod@googlemail.com'
- git config --global push.default 'simple'
- pip install --upgrade pip wheel
- echo -e 'Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git remote rm origin
- git remote add origin git@github.com:MatsLanGoH/matslangoh.github.io.git
- git fetch origin master
- git branch master FETCH_HEAD
install:
- pip install 'Nikola[extras]'
script:
- nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
notifications:
  email:
    on_success: change
    on_failure: always
